[MOSIP-28241] ] updated workflows with reusable template
mosip/tusd pull request #4
Opened 2023-09-13 12:47 UTC by Prafulrakhade

2023-09-13 12:51 UTC, syedsalman3753 requested changes

2023-09-13 12:51 UTC, syedsalman3753 commented on .github/workflows/push-trigger.yml
> +      - MOSIP*
please the selection section to `*`

2023-09-13 13:06 UTC, syedsalman3753 approved these changes

2023-09-14 05:34 UTC, ckm007 commented on .github/workflows/push-trigger.yml
> +      - '!release-branch'
MOSIP*
1.*
!release-branch
develop
master

2023-09-14 06:46 UTC, ckm007 approved these changes

2023-09-14 06:46 UTC, merged